language: php

php:
  - '5.6'
  - '7.0'
  - hhvm

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer self-update
  - composer install --prefer-dist --no-interaction
  - composer test-install

script: composer test
